version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    versioning-strategy: "increase"
    cooldown:
      default-days: 1
    groups:
      all-dependencies:
        patterns:
          - "*"
