packages:
  - apps/**
  - packages/*

autoInstallPeers: true

catalogs:
  appui:
    '@itwin/appui-react': ^5.28.1
    '@itwin/components-react': ^5.28.1
    '@itwin/core-react': ^5.28.1
    '@itwin/imodel-components-react': ^5.28.1
  build-tools:
    '@itwin/build-tools': 5.10.0-dev.1
    '@itwin/eslint-plugin': ^6.1.0
    '@rolldown/plugin-babel': ^0.2.3
    '@stylistic/eslint-plugin': ^5.10.0
    '@types/node': ^24.12.2
    '@vitejs/plugin-react': ^6.0.1
    babel-plugin-react-compiler: ^1.0.0
    cpx2: ^7.0.2
    cross-env: ^7.0.3
    eslint: ^9.39.4
    eslint-plugin-react: ^7.37.5
    eslint-plugin-unused-imports: ^4.4.1
    fast-glob: ^3.3.3
    rimraf: ^6.1.3
    tsdown: ^0.21.10
    typescript: ~6.0.3
    vite: ^8.0.10
    vite-plugin-static-copy: ^4.1.0
  itwinjs-core:
    '@itwin/core-bentley': ^5.8.4
    '@itwin/core-common': ^5.8.4
    '@itwin/core-geometry': ^5.8.4
  itwinjs-core-dev:
    '@itwin/appui-abstract': 5.10.0-dev.1
    '@itwin/core-backend': 5.10.0-dev.1
    '@itwin/core-bentley': 5.10.0-dev.1
    '@itwin/core-common': 5.10.0-dev.1
    '@itwin/core-electron': 5.10.0-dev.1
    '@itwin/core-frontend': 5.10.0-dev.1
    '@itwin/core-geometry': 5.10.0-dev.1
    '@itwin/core-i18n': 5.10.0-dev.1
    '@itwin/core-orbitgt': 5.10.0-dev.1
    '@itwin/core-quantity': 5.10.0-dev.1
    '@itwin/ecschema-metadata': 5.10.0-dev.1
    '@itwin/ecschema-rpcinterface-common': 5.10.0-dev.1
    '@itwin/ecschema-rpcinterface-impl': 5.10.0-dev.1
    '@itwin/express-server': 5.10.0-dev.1
    '@itwin/presentation-backend': 5.10.0-dev.1
    '@itwin/presentation-common': 5.10.0-dev.1
    '@itwin/presentation-frontend': 5.10.0-dev.1
    inversify: ~6.0.2
    reflect-metadata: ^0.1.14
  itwinui:
    '@itwin/itwinui-icons-react': ^2.11.0
    '@itwin/itwinui-illustrations-react': ^2.1.0
    '@itwin/itwinui-react': ^3.20.2
  react:
    '@types/react': ^18.3.28
    '@types/react-dom': ^18.3.7
    classnames: ^2.5.1
    react: ^18.3.1
    react-compiler-runtime: ^1.0.0
    react-dom: ^18.3.1
    react-error-boundary: ^4.1.2
  rxjs:
    rxjs: ^7.8.2
    rxjs-for-await: ^1.0.0
  stratakit:
    '@stratakit/bricks': ^0.5.4
    '@stratakit/foundations': ^0.4.8
    '@stratakit/icons': ^0.3.1
    '@stratakit/structures': ^0.5.7
  test-tools:
    '@testing-library/dom': ^10.4.1
    '@testing-library/react': ^16.3.2
    '@testing-library/user-event': ^14.6.1
    '@types/deep-equal-in-any-order': ^1.0.4
    '@vitest/browser-playwright': ^4.1.5
    '@vitest/coverage-v8': ^4.1.5
    axe-core: ^4.11.4
    deep-equal-in-any-order: ^2.2.0
    happy-dom: ^20.9.0
    playwright: ^1.59.1
    vitest: ^4.1.5
    vitest-browser-react: ^2.2.0

hoistPattern:
  - '!*'
  - '@types/react'
  - '@typescript-eslint/types'
  - '*babel*'
  - ignore-styles
  - global-jsdom

onlyBuiltDependencies:
  - '@bentley/imodeljs-native'
  - "@playwright/browser-chromium"
  - electron
  - esbuild

resolutionMode: lowest-direct

strictPeerDependencies: false
