packages:
  - apps/**
  - packages/*

autoInstallPeers: true

catalogs:
  appui:
    '@itwin/appui-react': ^5.23.0
    '@itwin/components-react': ^5.23.0
    '@itwin/core-react': ^5.23.0
    '@itwin/imodel-components-react': ^5.23.0
  build-tools:
    '@itwin/build-tools': ^5.5.1
    '@itwin/eslint-plugin': 5.1.0
    '@types/node': ^22.19.7
    "@stylistic/eslint-plugin": "^5.7.1"
    cpx2: ^7.0.2
    cross-env: ^7.0.3
    eslint: ^9.39.2
    eslint-plugin-react: ^7.37.5
    "eslint-plugin-unused-imports": "^4.3.0"
    rimraf: ^6.1.2
    typescript: ~5.7.3
  itwinjs-core:
    '@itwin/core-bentley': ^5.5.1
    '@itwin/core-common': ^5.5.1
    '@itwin/core-geometry': ^5.5.1
  itwinjs-core-dev:
    '@itwin/appui-abstract': ^5.6.0-dev.8
    '@itwin/core-backend': ^5.6.0-dev.8
    '@itwin/core-bentley': ^5.6.0-dev.8
    '@itwin/core-common': ^5.6.0-dev.8
    '@itwin/core-electron': ^5.6.0-dev.8
    '@itwin/core-frontend': ^5.6.0-dev.8
    '@itwin/core-geometry': ^5.6.0-dev.8
    '@itwin/core-i18n': ^5.6.0-dev.8
    '@itwin/core-orbitgt': ^5.6.0-dev.8
    '@itwin/core-quantity': ^5.6.0-dev.8
    '@itwin/ecschema-metadata': ^5.6.0-dev.8
    '@itwin/ecschema-rpcinterface-common': ^5.6.0-dev.8
    '@itwin/ecschema-rpcinterface-impl': ^5.6.0-dev.8
    '@itwin/express-server': ^5.6.0-dev.8
    '@itwin/presentation-backend': ^5.6.0-dev.8
    '@itwin/presentation-common': ^5.6.0-dev.8
    '@itwin/presentation-frontend': ^5.6.0-dev.8
    inversify: ~6.0.2
    reflect-metadata: ^0.1.14
  itwinui:
    '@itwin/itwinui-icons-react': ^2.11.0
    '@itwin/itwinui-illustrations-react': ^2.1.0
    '@itwin/itwinui-react': ^3.20.1
  react:
    '@types/react': ^18.3.27
    '@types/react-dom': ^18.3.7
    classnames: ^2.5.1
    react: ^18.3.1
    react-dom: ^18.3.1
    react-error-boundary: ^4.1.2
  rxjs:
    rxjs: ^7.8.2
    rxjs-for-await: ^1.0.0
  stratakit:
    '@stratakit/bricks': ^0.5.4
    '@stratakit/foundations': ^0.4.5
    '@stratakit/icons': ^0.2.2
    '@stratakit/structures': ^0.5.4
  test-tools:
    '@testing-library/dom': ^10.4.1
    '@testing-library/react': ^16.3.1
    '@testing-library/user-event': ^14.6.1
    '@types/chai': ^5.2.3
    '@types/chai-as-promised': ^8.0.2
    '@types/chai-jest-snapshot': ^1.3.8
    '@types/deep-equal-in-any-order': ^1.0.4
    '@types/jsdom': ^21.1.7
    '@types/mocha': ^10.0.10
    '@types/sinon': ^17.0.4
    '@types/sinon-chai': ^4.0.0
    c8: ^10.1.3
    chai: ^5.3.3
    chai-as-promised: ^8.0.2
    chai-jest-snapshot: ^2.0.0
    deep-equal-in-any-order: ^2.1.0
    global-jsdom: ^26.0.0
    ignore-styles: ^5.0.1
    jsdom: ^26.1.0
    mocha: ^11.7.5
    sinon: ^19.0.5
    sinon-chai: ^4.0.1

hoistPattern:
  - '!*'
  - '@types/react'
  - '@typescript-eslint/types'
  - '*babel*'
  - ignore-styles
  - global-jsdom

onlyBuiltDependencies:
  - '@bentley/imodeljs-native'
  - electron
  - esbuild

resolutionMode: lowest-direct

strictPeerDependencies: true
