packages:
 - apps/**
 - packages/*

catalogs:
  itwinjs-core:
    "@itwin/appui-abstract": "^4.9.0"
    "@itwin/core-backend": "^4.9.0"
    "@itwin/core-bentley": "^4.9.0"
    "@itwin/core-common": "^4.9.0"
    "@itwin/core-electron": "^4.9.0"
    "@itwin/core-frontend": "^4.9.0"
    "@itwin/core-geometry": "^4.9.0"
    "@itwin/core-i18n": "^4.9.0"
    "@itwin/core-orbitgt": "^4.9.0"
    "@itwin/core-quantity": "^4.9.0"
    "@itwin/core-telemetry": "^4.9.0"
    "@itwin/ecschema-metadata": "^4.9.0"
    "@itwin/ecschema-rpcinterface-common": "^4.9.0"
    "@itwin/ecschema-rpcinterface-impl": "^4.9.0"
    "@itwin/express-server": "^4.9.0"
    "@itwin/presentation-backend": "^4.9.0"
    "@itwin/presentation-common": "^4.9.0"
    "@itwin/presentation-frontend": "^4.9.0"
    "@itwin/webgl-compatibility": "^4.9.0"

  appui:
    "@itwin/appui-react": "^4.17.0"
    "@itwin/core-react": "^4.17.0"
    "@itwin/components-react": "^4.17.0"
    "@itwin/imodel-components-react": "^4.17.0"

  react:
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "@types/react": "^18.3.3"
    "@types/react-dom": "^18.3.0"

  test-tools:
    "@testing-library/dom": "^10.3.2"
    "@testing-library/react": "^16.0.0"
    "@testing-library/user-event": "^14.5.2"
    "@types/chai": "^4.3.16"
    "@types/chai-as-promised": "^7.1.8"
    "@types/chai-jest-snapshot": "^1.3.8"
    "@types/chai-subset": "^1.3.5"
    "@types/jsdom": "^21.1.7"
    "@types/mocha": "^10.0.7"
    "@types/sinon": "^17.0.3"
    "@types/sinon-chai": "^3.2.12"
    "chai": "^4.4.1"
    "chai-as-promised": "^7.1.2"
    "chai-jest-snapshot": "^2.0.0"
    "chai-subset": "^1.6.0"
    "global-jsdom": "^24.0.0"
    "ignore-styles": "^5.0.1"
    "jsdom": "^24.1.0"
    "mocha": "^10.6.0"
    "nyc": "^17.0.0"
    "sinon": "^18.0.0"
    "sinon-chai": "^3.7.0"

  dev-tools:
    "@itwin/build-tools": "^4.9.0"
    "@itwin/eslint-plugin": "^4.1.1"
    "@types/node": "^20.12.12"
    "cpx2": "^7.0.1"
    "cross-env": "^7.0.3"
    "eslint": "^8.57.0"
    "rimraf": "^6.0.1"
    "typescript": "~5.5.3"
