packages:
 - apps/**
 - packages/*

catalogs:
  itwinjs-core:
    "@itwin/appui-abstract": "^4.10.1"
    "@itwin/core-backend": "^4.10.1"
    "@itwin/core-bentley": "^4.10.1"
    "@itwin/core-common": "^4.10.1"
    "@itwin/core-electron": "^4.10.1"
    "@itwin/core-frontend": "^4.10.1"
    "@itwin/core-geometry": "^4.10.1"
    "@itwin/core-i18n": "^4.10.1"
    "@itwin/core-orbitgt": "^4.10.1"
    "@itwin/core-quantity": "^4.10.1"
    "@itwin/core-telemetry": "^4.10.1"
    "@itwin/ecschema-metadata": "^4.10.1"
    "@itwin/ecschema-rpcinterface-common": "^4.10.1"
    "@itwin/ecschema-rpcinterface-impl": "^4.10.1"
    "@itwin/express-server": "^4.10.1"
    "@itwin/presentation-backend": "^4.10.1"
    "@itwin/presentation-common": "^4.10.1"
    "@itwin/presentation-frontend": "^4.10.1"
    "@itwin/webgl-compatibility": "^4.10.1"
    "inversify": "~6.0.2"
    "reflect-metadata": "^0.1.14"

  appui:
    "@itwin/appui-react": "^4.17.5"
    "@itwin/core-react": "^4.17.5"
    "@itwin/components-react": "^4.17.5"
    "@itwin/imodel-components-react": "^4.17.5"

  itwinui:
    "@itwin/itwinui-icons-react": "^2.9.0"
    "@itwin/itwinui-illustrations-react": "^2.1.0"
    "@itwin/itwinui-react": "^3.15.5"

  react:
    "classnames": "^2.5.1"
    "react-error-boundary": "^4.0.13"
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "@types/react": "^18.3.3"
    "@types/react-dom": "^18.3.0"

  rxjs:
    "rxjs": "^7.8.1"
    "rxjs-for-await": "^1.0.0"

  test-tools:
    "@testing-library/dom": "^10.3.2"
    "@testing-library/react": "^16.0.0"
    "@testing-library/user-event": "^14.5.2"
    "@types/chai": "^4.3.16"
    "@types/chai-as-promised": "^7.1.8"
    "@types/chai-jest-snapshot": "^1.3.8"
    "@types/chai-subset": "^1.3.5"
    "@types/jsdom": "^21.1.7"
    "@types/mocha": "^10.0.7"
    "@types/sinon": "^17.0.3"
    "@types/sinon-chai": "^3.2.12"
    "c8": "^10.1.2"
    "chai": "^4.4.1"
    "chai-as-promised": "^7.1.2"
    "chai-jest-snapshot": "^2.0.0"
    "chai-subset": "^1.6.0"
    "global-jsdom": "^25.0.0"
    "ignore-styles": "^5.0.1"
    "jsdom": "^25.0.1"
    "mocha": "^10.7.3"
    "sinon": "^18.0.0"
    "sinon-chai": "^3.7.0"
    "testdouble": "^3.20.2"

  build-tools:
    "@itwin/build-tools": "^4.10.1"
    "@itwin/eslint-plugin": "5.0.0-dev.1"
    "@types/node": "^20.12.12"
    "cpx2": "^7.0.1"
    "cross-env": "^7.0.3"
    "eslint": "^9.13.0"
    "eslint-plugin-react": "^7.37.2"
    "rimraf": "^6.0.1"
    "typescript": "~5.6.3"
