trigger:
  branches:
    include:
      - master
      - stable

pr:
  drafts: true
  branches:
    include:
      - master
      - stable

resources:
  repositories:
    - repository: itwinjs-core
      type: github
      endpoint: iModelJs
      name: iTwin/itwinjs-core
      ref: refs/heads/master

stages:
  - stage: Check_Changes
    jobs:
    - job: docs_modified
      steps:
      - checkout: self
        fetchDepth: 0
        clean: true

      - powershell: |
          $paths = "packages/components/*", "packages/testing/*", "packages/opentelemetry/*", "apps/test-app/*", "apps/full-stack-tests/src/components/*", "apps/full-stack-tests/src/testing/*"
          $sourceBranch = "$(System.PullRequest.SourceBranch)"
          $targetBranch = "$(System.PullRequest.targetBranchName)"
          $diff=$(git diff --name-only $(git merge-base $targetBranch $sourceBranch))
          $files=$diff -split ' '
          foreach ($file in $files) {
            foreach ($path in $paths) {
              if ($file -like $path) {
                Write-Host "Docs modified"
                Write-Host "##vso[task.setvariable variable=docsModified;isOutput=true]True"
                Return
              }
            }
          }
          Write-Host "Docs not modified"
        name: filter_paths

  - stage: Generate_Docs
    dependsOn: Check_Changes
    condition: |
      and(
        succeeded(),
        or(
          ne(variables['Build.Reason'], 'PullRequest'),
          eq(dependencies.Check_Changes.outputs['docs_modified.filter_paths.docsModified'], 'true')
        )
      )
    jobs:
      - job: DocsGenerate
        displayName: Generate Docs
        workspace:
          clean: all

        steps:
          - checkout: self
            clean: true

          - task: NodeTool@0
            displayName: Use Node 20
            inputs:
              versionSpec: 20
              checkLatest: true

          - script: npm install -g pnpm@9
            displayName: Install pnpm

          - script: pnpm install
            displayName: Run 'pnpm install'

          - script: pnpm docs:all
            displayName: Run 'pnpm docs:all'
            env:
              RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)

          - script: pnpm gather-docs
            displayName: Run 'pnpm gather-docs'

          - task: CopyFiles@2
            displayName: 'Copy generated docs to: $(Build.StagingDirectory)'
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/build
              TargetFolder: $(Build.StagingDirectory)

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: Presentation Docs'
            inputs:
              PathtoPublish: '$(Build.StagingDirectory)/docs/'
              ArtifactName: 'Presentation Docs'

  - stage: Validate_Docs
    dependsOn: Generate_Docs
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'PullRequest', 'Manual'))
    jobs:
      - template: common/config/azure-pipelines/jobs/docs-build.yaml@itwinjs-core
        parameters:
          checkout: itwinjs-core
          ignoreAudit: true
          useCurrentPresentationDocsArtifact: true

  - stage: Tag_Docs
    dependsOn: Validate_Docs
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'Manual'))
    jobs:
      - job:
        displayName: Tag Docs
        steps:
          - task: tagBuildOrRelease@0
            displayName: Tag Docs
            inputs:
              type: "Build"
              tags: "hasDocs"
            condition: and(contains(variables['Build.SourceVersionMessage'], '[publish docs]'), not(contains(variables['Build.SourceVersionMessage'], '(dev)')))
