name: PR hierarchies performance benchmark

on:
  pull_request:
    branches:
      - master
      - stable
    paths:
      - apps/performance-tests/hierarchies/**
      - apps/performance-tests/util/**
      - packages/core-interop/**
      - packages/hierarchies/**
      - packages/models-tree/**
      - packages/shared/**
      - pnpm-lock.yaml
      - .github/workflows/benchmark-pr-hierarchies.yml
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  benchmark:
    name: 'Hierarchies: Benchmark performance'
    if: 'github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.5

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build benchmark tests
        run: pnpm lage build --to presentation-performance-tests

      - name: Restore dataset from cache
        uses: actions/cache/restore@v4
        id: cache-restore
        env:
          cache-name: cache-dataset
        with:
          path: "./apps/performance-tests/datasets/*.bim"
          key: performance-test-dataset-${{ hashFiles('./apps/performance-tests/src/util/Datasets.ts') }}

      - name: Run benchmark tests
        run: pnpm benchmark:hierarchies

      - name: Save generated datasets
        uses: actions/cache/save@v4
        if: steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: "./apps/performance-tests/datasets/*.bim"
          key: performance-test-dataset-${{ hashFiles('./apps/performance-tests/src/util/Datasets.ts') }}

      - name: Post benchmark summary
        uses: JonasDov/github-action-benchmark@a1808b2b798a9befa6b3c9988f2ad26b78ccb0cd
        with:
          name: Hierarchies benchmark
          tool: 'customSmallerIsBetter'
          output-file-path: ./apps/performance-tests/hierarchies-benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          save-data-file: false
          comment-on-pull-request: true
