name: PR performance benchmark

on:
  pull_request:
    branches:
      - master
      - stable
    paths:
      - apps/performance-tests/**
      - packages/core-interop/**
      - packages/hierarchies/**
      - packages/models-tree/**
      - pnpm-lock.yaml
      - .github/workflows/benchmark-pr.yml
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  benchmark:
    name: Benchmark performance
    # if: '!github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.1

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build benchmark tests
        run: pnpm lage build --to presentation-performance-tests

      - name: Restore dataset from cache
        uses: actions/cache/restore@v3
        id: cache-restore
        env:
          cache-name: cache-dataset
        with:
          path: "./apps/performance-tests/datasets/*.bim"
          key: performance-test-dataset-${{ hashFiles('./apps/performance-tests/src/Datasets.ts') }}

      - name: Run benchmark tests
        run: pnpm benchmark

      - name: Save generated datasets
        uses: actions/cache/save@v3
        if: steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: "./apps/performance-tests/datasets/*.bim"
          key: performance-test-dataset-${{ hashFiles('./apps/performance-tests/src/Datasets.ts') }}

      - name: Post benchmark summary
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customSmallerIsBetter'
          output-file-path: ./apps/performance-tests/benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # comment-always: true
          summary-always: true
