name: Performance benchmark
on:
  pull_request:
#  push:
#    branches:
#      - master
jobs:
  benchmark:
    name: Benchmark performance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build benchmark tests
        run: pnpm lage build --to @load-tests/backend @load-tests/frontend

      - name: Run benchmark tests
        run: npm run benchmark

      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./.cache
          key: benchmark-data.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customSmallerIsBetter'
          output-file-path: ./apps/load-tests/tests/benchmark.json
          external-data-json-path: ./.cache/benchmark-data.json
          save-data-file: true
