name: CI

on:
  pull_request:
    branches: ["master", "stable", "components-major-bump"] # TODO: remove before master merge
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint Build and run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093

      - name: Use Node.js 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24.15.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run oxfmt
        run: pnpm format

      - name: Run cspell
        run: pnpm cspell

      - name: Build, Lint, Test
        env:
          NODE_ENV: "development"
        run: pnpm lage build lint cover

  docs:
    runs-on: ubuntu-latest
    name: Validate docs
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093

      - name: Use Node.js 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24.15.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check code snippets
        run: pnpm check-extractions

      - name: Validate markdowns
        run: pnpm validate-markdowns
