# iTwin.js Extract API Build

name: Extract API

on:
  pull_request:
    branches:
      - master
      - stable
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  files-changed:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    name: Detect what files changed
    outputs:
      packages: ${{ steps.changes.outputs.packages }}
      workspace_config: ${{ steps.changes.outputs.workspace_config }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Check for file changes
        uses: dorny/paths-filter@9d7afb8d214ad99e78fbd4247752c4caed2b6e4c
        id: changes
        with:
          filters: |
            packages:
              - 'packages/**'
            workspace_config:
              - 'pnpm-workspace.yaml'

  extract-api:
    needs: [files-changed]
    if: ${{ needs.files-changed.outputs.packages == 'true' || needs.files-changed.outputs.workspace_config == 'true' }}
    runs-on: ubuntu-latest
    name: Extract API
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093

      - name: Use Node.js 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24.15.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Extract API
        env:
          TF_BUILD: 1
        run: pnpm lage extract-api check-internal
