name: Publish dev pre-release NPM packages

on:
  workflow_dispatch:

jobs:
  release-packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    name: Release packages
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.17.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: pnpm install

    - name: Build, Lint, Test
      run: pnpm lage build lint cover

    - name: Publish packages
      run: |
        git config --local user.email imodeljs-admin@users.noreply.github.com
        git config --local user.name imodeljs-admin
        pnpm publish-packages-dev -y --branch ${{ github.ref_name }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
