name: Release

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Branch that should be used to perform publish on"
        required: true
        type: string

jobs:
  release-packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    name: Release packages
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.target }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.17.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: pnpm install

    - name: Build, Lint, Test
      run: pnpm lage build lint cover

    - name: Publish packages
      run: pnpm publish-packages -y --no-publish --branch ${{ inputs.target }}
      # env:
      #   NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
