name: Skip checks
on:
  pull_request:
    branches:
      - master
      - stable
jobs:
  Generate_Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0

  Validate_Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0
