name: Azure Pipelines
on:
  pull_request:
    branches:
      - master
      - stable
jobs:
  iTwin Presentation Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0
