name: PR unified-selection performance benchmark

on:
  pull_request:
    branches:
      - master
      - stable
    paths:
      - apps/performance-tests/**
      - packages/unified-selection/**
      - pnpm-lock.yaml
      - .github/workflows/unified-selection-benchmark-pr.yml
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  benchmark:
    name: Benchmark performance (unified-selection)
    #if: '!github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.1

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build benchmark tests
        run: pnpm lage build --to presentation-performance-tests

      - name: Restore dataset from cache
        uses: actions/cache/restore@v4
        id: cache-restore
        env:
          cache-name: cache-dataset
        with:
          path: "./apps/performance-tests/datasets/*.bim"
          key: performance-test-dataset-${{ hashFiles('./apps/performance-tests/src/Datasets.ts') }}

      - name: Run benchmark tests
        run: pnpm benchmark:unified-selection

      - name: Save generated datasets
        uses: actions/cache/save@v4
        if: steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: "./apps/performance-tests/datasets/*.bim"
          key: performance-test-dataset-${{ hashFiles('./apps/performance-tests/src/Datasets.ts') }}

      - name: Post unified-selection benchmark summary
        uses: jalextowle/github-action-benchmark@35e54a2ea34188ca73481c2a0ce5919907978f4f
        with:
          name: 'unified-selection benchmark'
          tool: 'customSmallerIsBetter'
          output-file-path: ./apps/performance-tests/unified-selection-benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          save-data-file: false
          comment-on-pull-request: true
